export const SET_CONTACT_NAME = 'SET_CONTACT_NAME';
export const SET_CONTACT_TO_HEADER_RENDER = 'SET_CONTACT_TO_HEADER_RENDER';
export const SET_MESSAGE_TO_MESSAGE_HISTORY = 'SET_MESSAGE_TO_MESSAGE_HISTORY';
export const SET_MESSAGE_FROM_API = 'SET_MESSAGE_FROM_API';